# Generated by Django 3.2.3 on 2021-06-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_follow_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
