# Generated by Django 3.2.3 on 2021-06-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210602_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text='Опишите суть группы', verbose_name='Текст'),
        ),
    ]
